Introducing new parameter to rouge: gpt_uuid
xen-troops/moulin pull request #41
Opened 2022-05-23 16:13 UTC by oleksiimoisieiev

gpt_uuid parameter is intendend to set UUID for gpt partitions. Partition UUID can be used to mount partition from fstab regardless of the storage type.

2022-05-23 18:39 UTC, lorc requested changes
Please combine both commits into one.

We want documentation to be added along with the feature in the same commit.

2022-05-23 18:39 UTC, lorc commented on moulin/rouge/block_entry.py
> +    gpt_uuid: str
It is GUID, not UUID.

Better name would be `part_guid` to denote that this is partition GUID.

2022-05-23 18:39 UTC, lorc commented on moulin/rouge/sfdisk.py
> +    if part.gpt_uuid != "":
This should be `if part.gpt_uuid: `

2022-05-23 18:39 UTC, lorc commented on moulin/rouge/sfdisk.py
> +        result = ", ".join([result, f"uuid={part.gpt_uuid}"])
Ugh.

We should rework this whole function.

Something like this will be much nicer:

```
    args = [
        f"start={_sect(part.start, sector_size)}", f"size={_sect(part.size, sector_size)}",
        f"type={part.gpt_type}", f"name={part.label}"
    ]

    if part.part_guid:
        args.append(f"uuid={part.part_guid}")

    return ", ".join(args)

```

2022-05-24 07:02 UTC, oleksiimoisieiev commented on docs/rouge.rst
> +regardless of storage type.
The main idea of partition uuids and labels is that you can access to partition using some predefined name or id.
So for example: traditional way to mount partition in fstab is /dev/mmcblk0p1 or /dev/nvme...
Using PARTUUID= in fstab saves us from changing fstab each time we change storage. So we can use one image, written to /dev/mmcblk*, /dev/nvme0n*, /dev/ssd*.

Rouge already have part label, but I had to add part_uuid - because MTA has swupdate project, which does A/B update and those partition UUIDs are hardcoded to swupdate application.

2022-05-24 07:04 UTC, oleksiimoisieiev commented on moulin/rouge/block_entry.py
> +    gpt_uuid: str
I would disagree with that. sfdisk parameter is called uuid, fdisk entry also named as PARTUUID. The Idea of GUID is that this is global unique identifier. We can't say that partition id is globally unique.

2022-05-24 07:53 UTC, oleksiimoisieiev commented on moulin/rouge/block_entry.py
> +    gpt_uuid: str
I was wrong. https://en.wikipedia.org/wiki/GUID_Partition_Table says that 0x16 position called Partition GUID on Windows manner. I will rename.

2022-05-24 08:05 UTC, lorc commented on docs/rouge.rst
> +regardless of storage type.
> Rouge already have part label, but I had to add part_uuid - because MTA has swupdate project, which does A/B update and those partition UUIDs are hardcoded to swupdate application.

Well, this is the good reason and good example. You can use this in the documentation:

```:code:`part_guid:` key sets partition GUID. Usually this GUID is generated automatically to ensure that every partition in the world have unique identifier. But there are some cases when external software depends on exact value of a partition GUID. In such cases it is possible to hard-code this value.```

2022-05-24 08:08 UTC, oleksiimoisieiev commented on moulin/rouge/sfdisk.py
> +    if part.gpt_uuid != "":
fixed

2022-05-24 08:08 UTC, oleksiimoisieiev commented on moulin/rouge/block_entry.py
> +    gpt_uuid: str
fixed

2022-05-24 08:08 UTC, oleksiimoisieiev commented on moulin/rouge/sfdisk.py
> +        result = ", ".join([result, f"uuid={part.gpt_uuid}"])
fixed

2022-05-24 08:26 UTC, lorc commented on docs/rouge.rst
> +       gpt_guid: 8DA63339-0007-60C0-C436-083AC823090 # Partition GUID
Why it is one digit shorter than `gpt_type`?

2022-05-24 08:26 UTC, lorc commented on docs/rouge.rst
> +(but we strongly suggest to provide them) keys:
I strongly suggest to provide `gpt_type` and strongly suggest to NOT provide `gpt_guid` unless it is strictly necessary. People just love to copy and paste. Any hard-coded partition GUID will spread across all projects. We don't want this.

2022-05-24 08:26 UTC, lorc commented on docs/rouge.rst
> +
Why two line breaks?

2022-05-24 08:27 UTC, lorc commented
BTW, you can run pylint locally ;)

2022-05-24 08:28 UTC, lorc commented on docs/rouge.rst
> +partition regardless of the storage type. Details could be found on:
> regardless of the storage type

What this means? I don't get it.

2022-05-24 11:03 UTC, oleksiimoisieiev commented on docs/rouge.rst
> +       gpt_guid: 8DA63339-0007-60C0-C436-083AC823090 # Partition GUID
Fixed

2022-05-24 11:05 UTC, oleksiimoisieiev commented on docs/rouge.rst
> +
Fixed

2022-05-24 12:15 UTC, lorc commented
`Reviewed-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

2022-05-24 12:16 UTC, lorc approved these changes

2022-05-24 12:32 UTC, merged