[WIP] Add fetcher and builder for Zephyr OS
xen-troops/moulin pull request #43
Opened 2022-07-14 05:01 UTC by rshym

Fetcher for west meta-tool
  type: west
  `url` is optional and corresponds to `west init -m`
  `rev` is optional and corresponds to `west init --mr`
  `file` is optional and corresponds to `west init --mf`
Beside sources, fetcher also fetches required version of CMake.

Builder:
  type: zephyr
  board: <any supported board>
  target: <samples/...>
  sdk: <path to preinstalled SDK>
  target_images: zephyr.bin

For additional info, please see
https://docs.zephyrproject.org/latest/develop/getting_started/index.html

Signed-off-by: Ruslan Shymkevych <ruslan_shymkevych@epam.com>

2022-07-14 05:05 UTC, rshym commented
PR contains working code, that fetches and builds as expected.
But it needs some additional work, especially in part related to external tools.

2022-07-19 10:52 UTC, lorc requested changes
Please update documentation in the same patch.

Also, you can split this PR into two patches:

1. fetcher + documentation
2. builder + documentation

2022-07-19 10:52 UTC, lorc commented on moulin/builders/zephyr.py
> +        "export PATH=$abs_cmake_path:$$PATH",
Why we can't use `cmake` from host?

2022-07-19 10:52 UTC, lorc commented on moulin/builders/zephyr.py
> +            "sdk": os.path.abspath(self.conf["sdk"].as_str),
Do we really need to provide path to SDK? Looks like `west` can determine SDK location automatically. 
I want YAML files to be environment-agnostic. Forcing user to update YAML for own environment is not a good idea.

2022-07-19 10:52 UTC, lorc commented on moulin/fetchers/west.py
> +        "wget -q $cmake_url",
Not all distributions have wget installed by default. Instead of forcing user to install wget, it is easier to make them install cmake directly :)

2022-07-19 10:52 UTC, lorc commented on moulin/fetchers/west.py
> +        return []
Well, it would be good to implement this. Otherwise ninja will not track changes into source code and will not rebuild zephyr, which will hinder development.

2022-07-20 13:34 UTC, lorc commented
Sorry for late comment, but you also need to bump up version of Moulin to ensure that `min_version` is properly used/working in YAML files.

2022-07-22 14:28 UTC, rshym commented on moulin/fetchers/west.py
> +        return []
get_file_list() is implemented together with corresponding part of builder.
Tested successfully: I have added whitespace to one of the sources, and ninja noticed the change and ran the build.

2022-07-22 14:29 UTC, rshym commented
Documentation is added.
Version is bumped to 0.8.
All comments seem to be addressed.

2022-07-24 20:14 UTC, lorc approved these changes
`Reviewed-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

2022-07-25 07:02 UTC, rshym commented
RB is added.
PR is ready to be merged.

2022-07-25 10:43 UTC, merged