rouge: add possibility to specify size of image
xen-troops/moulin pull request #50
Opened 2022-09-20 09:15 UTC by rshym

For some cases we need to have image of certain size despite sizes of internal partitions.

This PR adds `image_size` field to image descriptor. If it is not specified or zero, then image is created taking into account internal partitions.
If actual size of partitions is bigger than `image_size` - error is raised, that we can't create image of specified size.

2022-09-20 09:19 UTC, rshym commented
Generation of image was tested with this PR for a few cases:
- `image_size` is specified and is bigger than the actual image size - image has a specified size;
- `image_size` is specified and is smaller than the actual size - an exception is shown to the user, and no image is created;
- `image_size` is not specified - image has actual size.

2022-09-20 09:32 UTC, rshym commented
YAML with image_size looks like this:
```images:
  full:
    type: gpt
    image_size: 512 MiB
    desc: "Full SD-card/eMMC image"
    partitions:
```

2022-09-20 10:25 UTC, rshym commented
Rebased to latest `main`.

2022-09-20 10:31 UTC, lorc requested changes
Please update the documentation accordingly.

2022-09-20 10:31 UTC, lorc commented on moulin/rouge/block_entry.py
> +        self._requested_image_size: int = 0
Better to make it `Optional[int]` and test for `None` rather than for `0`

2022-09-21 00:03 UTC, rshym commented
Comments are addressed:
- `Optional[int]` is used and tested with and without image_size;
- documentation is updated.

2022-09-21 00:22 UTC, rshym commented
Update.
- Reference to 'Size Designation' section is added
- VS Code editor showed me a notification that 'The character U+00a0 is invisible.' So I replaced that invisible char with regular whitespace.

2022-09-21 08:14 UTC, lorc approved these changes
Please squash the two commits together.

In most cases it is good to have functional and documentation changes in the same commit because:

1) It helps to document changes made by commit

2) Both changes can be reverted at the same time

WIth that:

`Reviewed-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

2022-09-21 10:23 UTC, rshym commented
RB is added.
Successfully tested with
- image_size not specified
- image_size < actual size
- image_size => actual size

Ready to be merged.

2022-09-21 10:25 UTC, merged