zephyr: add ext_files option to builder
xen-troops/moulin pull request #63
Opened 2022-12-18 22:07 UTC by rshym

Contains commit from not merged PR #62.

---

This option allows to collect external files that are required for the build.
Example of corresponding yaml:

```
  builder:
    type: zephyr
    ...
    ext_files:
      "dest_file_1": "path/to/external/file_1"
      "abc/file_BB": "path/to/external/file_2"
```
Destination directories are created if specified.
File may be renamed to desired destination name.

Signed-off-by: Ruslan Shymkevych <ruslan_shymkevych@epam.com>

2022-12-18 22:10 UTC, rshym commented
Tested with yaml containg:
```
      ext_files:
        # destination paths are relative to %{build-dir}
        "xenutils/include/domain_bins/domd_img.bin": "%{YOCTOS_WORK_DIR}/%{DOMD_BUILD_DIR}/tmp/deploy/images/%{MACHINE}/Image"
        "xenutils/include/domain_bins/domd.dtb": "%{YOCTOS_WORK_DIR}/%{DOMD_BUILD_DIR}/tmp/deploy/images/%{MACHINE}/%{XT_DOMD_DTB_NAME}"
        "xenutils/include/domain_bins/domu_img.bin": "%{YOCTOS_WORK_DIR}/%{DOMD_BUILD_DIR}/tmp/deploy/images/%{MACHINE}/Image"
        "xenutils/include/domain_bins/domu.dtb": "%{YOCTOS_WORK_DIR}/%{DOMD_BUILD_DIR}/tmp/deploy/images/%{MACHINE}/%{XT_DOMD_DTB_NAME}"
```
Also, tested:
- without destination directories
- with absence of `ext_files` (that why I have added `|| true")

2022-12-19 23:34 UTC, lorc commented on docs/user-reference.rst
> +* :code:`ext_files` - list of external files that need to be collected
Well, this is not a list. It is mapping. YAML uses a different syntax for lists

2022-12-19 23:34 UTC, lorc commented on docs/user-reference.rst
> +  relative to zephyr's `build-dir`, and can contain path. If destination
s/"can contain path"/"can include subdirectories" maybe?

2022-12-19 23:34 UTC, lorc commented on moulin/builders/zephyr.py
> +        "source " + SCRIPT_NAME_TO_PULL_BINS + " || true",
You could use string interpolation (aka f-string) there, but this is not the biggest problem.

I don't think we need a separate script there at all. We may just use variable there. It will be a bit less awful. Just replace this whole line with `($pull_ext_sources)` and then provide variable `pull_ext_sources` in `gen_build` with contents of your `SCRIPT_NAME_TO_PULL_BINS`

2022-12-19 23:34 UTC, lorc commented on moulin/builders/zephyr.py
> +                src_name = os.path.relpath(src_node.as_str, self.build_dir)
I believe we need to add each SRC to dependencies list, so Ninja will trigger rebuild if external file is changed.

2022-12-20 09:27 UTC, rshym commented on moulin/builders/zephyr.py
> +        "source " + SCRIPT_NAME_TO_PULL_BINS + " || true",
That was my initial idea, but I'm afraid that we may reach some limits if we will have 10+ files with long paths.
So I decided to use the external script which may handle any amount of files.
But I may be wrong regarding command-line limits.

2022-12-20 11:23 UTC, lorc commented on moulin/builders/zephyr.py
> +        "source " + SCRIPT_NAME_TO_PULL_BINS + " || true",
AFAI, command line limit in Linux is about 64 kbytes, which should be enough in all cases except Android builds :)

2022-12-21 14:48 UTC, rshym commented on docs/user-reference.rst
> +* :code:`ext_files` - list of external files that need to be collected
Thanks. This part if reworded.

2022-12-21 14:49 UTC, rshym commented on docs/user-reference.rst
> +  relative to zephyr's `build-dir`, and can contain path. If destination
Done.

2022-12-21 14:50 UTC, rshym commented on moulin/builders/zephyr.py
> +        "source " + SCRIPT_NAME_TO_PULL_BINS + " || true",
Reworked. The additional script is not used. All commands are put into the command line. Please see the comment in the code regarding the handling of empty `ext_files`.

2022-12-21 14:51 UTC, rshym commented on moulin/builders/zephyr.py
> +                src_name = os.path.relpath(src_node.as_str, self.build_dir)
Reworked. Tested. Build of DomD was initiated.

2022-12-26 15:07 UTC, lorc requested changes

2022-12-26 15:07 UTC, lorc commented on moulin/builders/zephyr.py
> +        script.append("cd zephyr")
Why do you need `cp zephyr` and end of the script?

2022-12-26 15:07 UTC, lorc commented on moulin/builders/zephyr.py
> +        # Variable 'pull_ext_sources' always has "cd zephyr" appended,
This is wrong. You are mixing two functionalities together.  Better leave `true` in the `pull_ext_sources`.

2023-01-20 09:05 UTC, rshym commented on moulin/builders/zephyr.py
> +                src_name = os.path.relpath(src_node.as_str, self.build_dir)
Comments are reworked.

2023-01-20 09:08 UTC, rshym commented on moulin/builders/zephyr.py
> +        script.append("cd zephyr")
This approach was reworked. Part of the "outer" build script is not mixed with "pull external files" anymore.

2023-01-20 09:08 UTC, rshym commented on moulin/builders/zephyr.py
> +        # Variable 'pull_ext_sources' always has "cd zephyr" appended,
This approach was reworked.

2023-04-03 09:36 UTC, closed without merging