New builder - fota
xen-troops/moulin pull request #72
Opened 2023-04-25 20:56 UTC by dsemenets

Fota builder is intended to create an over-the-air archive for update firmware

2023-04-25 22:42 UTC, lorc requested changes
Please remember that Moulin is a generic build system, that is intended to be used by external users. This is not part of our products, strictly speaking. 

So, we need to maintain certain level of quality while adding changes to it. At least, you need to provide an comprehensive documentation and name things in a such way, that it would be understandable for external user.

For this particular commit, I am asking you to rename this builder to "aos-fota" and write in the documentation that it is supposed to be used by AOS project. 

Also, I am asking you to consider the following: you are using external build script anyway. So there is no need to generate some files (like your manifest.json) via moulin/ninja. Just pass the whole build config to your script as YAML via command line option and let it handle all the details. You can use something like `yaml.serialize(self.conf._node)` to serialize config back into YAML. Contact me if you need details.

2023-04-25 22:42 UTC, lorc commented on docs/user-reference.rst
> +fota builder
"fota" is too generic. Maybe "aos-fota"?

2023-04-25 22:42 UTC, lorc commented on docs/user-reference.rst
> +Fota builder is intended to create an fota archive.
Please provide full documentation. I, for instance, have no idea what this builder is does

2023-04-25 22:42 UTC, lorc commented on docs/user-reference.rst
> +    name: "artifacts.tar.bz2"
What is the difference between `name` and `target_name`? Why they are different?

2023-04-25 22:42 UTC, lorc commented on docs/user-reference.rst
> +* :code:`build_script` - path to script which creates fota archive
Where this script can be obtained? What parameters it expects? What will it do?

2023-04-25 22:42 UTC, lorc commented on docs/user-reference.rst
> +* :code:`domd` - parameters, files, manifest items for create domd part of
So, you are limiting this builder to dom0 and domd? What if want to add additional domain in the future?

2023-04-25 22:42 UTC, lorc commented on docs/user-reference.rst
>  Proper versions of CMake and Zephyr SDK have to be installed on the host.
Sooo, you just put this "fota" section in the middle of zephyr builder documentation?

2023-04-25 22:42 UTC, lorc commented on moulin/builders/fota.py
> +Ota packer builder module
Ota?

2023-04-25 22:42 UTC, lorc commented on moulin/builders/fota.py
> +# Copyright 2022 EPAM Systems
It is 2023 already

2023-04-25 22:42 UTC, lorc commented on moulin/builders/fota.py
> +#            construct_fetcher_dep_cmd(),
Please don't add commented-out code

2023-04-25 22:42 UTC, lorc commented on moulin/builders/fota.py
> +            depfile=".moulin_$name.d",
I don't see that you generate dependency file, so you probably don't need this.

2023-04-25 22:42 UTC, lorc commented on moulin/builders/fota.py
> +    def _parse_node(self, dom_node):
Could you please provide correct typing hints?

2023-04-25 22:42 UTC, lorc commented on moulin/builders/fota.py
> +        if os.path.exists(work_dir):
Moulin is supposed to generate `build.ninja`. It should **not** alter any existing files on the file system.

Please remember that `moulin` is invoked only once. Then we just run `ninja` and it will not call `moulin` again if YAML file is not changed.

2023-04-25 22:42 UTC, lorc commented on moulin/builders/fota.py
> +        deps = list(self.src_stamps)
Are those all dependencies? Ninja will not rebuilt this FOTA package after a very first build. You need to include all your `items` into dependencies, so Ninja can track changes there and re-create the archive

2023-04-26 10:21 UTC, dsemenets commented on docs/user-reference.rst
> +    name: "artifacts.tar.bz2"
Sorry. This parameter is not used. I'll delete this

2023-04-26 10:23 UTC, dsemenets commented on docs/user-reference.rst
> +* :code:`build_script` - path to script which creates fota archive
This script actually creates archive. Ninja should call this script. Currently this script placed in meta-aos-rcar-deme2023 repository

2023-04-26 12:58 UTC, dsemenets commented on docs/user-reference.rst
> +* :code:`domd` - parameters, files, manifest items for create domd part of
For now - yes.

2023-04-26 13:02 UTC, lorc commented on docs/user-reference.rst
> +* :code:`domd` - parameters, files, manifest items for create domd part of
Could you just make it more generic right from the start? Please remember that Moulin is a separate project, not AOS submodule. I want it be well-designed from the very beginning.

2023-05-09 23:15 UTC, lorc commented
Before we begin review - could you please fix CI errors?

2023-05-10 16:29 UTC, dsemenets commented
I have fixed CI errors

2023-05-10 19:49 UTC, lorc reviewed
I want to test this PR. Could you please provide some instructions on how I can do this?

2023-05-10 19:49 UTC, lorc commented on docs/user-reference.rst
> +    type: fota        # Should be 'fota'
Please rename it to something more appropriate, like `aos_fota`

2023-05-10 19:49 UTC, lorc commented on docs/user-reference.rst
>  Proper versions of CMake and Zephyr SDK have to be installed on the host.
This comment still stands

2023-05-10 19:49 UTC, lorc commented on moulin/builders/fota.py
> +        "rm -rf $work_dir",
Do you really need to remove work dir every time? This is not the desired behaviour for any build system

2023-05-10 19:49 UTC, lorc commented on moulin/builders/fota.py
> +        conf_bytes = serialized_conf.encode("ascii")
I'd better stick to "utf8" just in case some will try to use non-ascii characters

2023-05-10 19:50 UTC, lorc commented on docs/user-reference.rst
> +* :code:`build_script` - path to script which creates fota archive
You need to describe this in the the documentation

2023-05-10 20:10 UTC, dsemenets commented on docs/user-reference.rst
> +fota builder
As I can see this is not only "fota" or "aos-fota". This is more generic thing.

2023-05-10 20:12 UTC, dsemenets commented on docs/user-reference.rst
> +Fota builder is intended to create an fota archive.
I removed options which moulin doesn't process itself.

2023-05-10 20:12 UTC, dsemenets commented on moulin/builders/fota.py
> +#            construct_fetcher_dep_cmd(),
Done

2023-05-10 20:12 UTC, dsemenets commented on moulin/builders/fota.py
> +            depfile=".moulin_$name.d",
Done

2023-05-10 20:13 UTC, dsemenets commented on moulin/builders/fota.py
> +        if os.path.exists(work_dir):
Done

2023-05-10 20:13 UTC, dsemenets commented on moulin/builders/fota.py
> +        deps = list(self.src_stamps)
Removed

2023-05-10 20:15 UTC, lorc commented on docs/user-reference.rst
> +fota builder
If this a more generic thing, we need a proper name for it. As I can see, it can be used for other tasks than FOTA. Maybe call it "custom_script" builder then?

2023-05-10 20:19 UTC, dsemenets commented on moulin/ninja_syntax.py
> +                while text[space] == ' ':
No. I don't want break line inside whitespace sequence. I want leave whole whitespace sequence before break.
BTW for now this patch is obsolete for purpose of this patch set builder. So I can remove it.

2023-05-10 20:28 UTC, dsemenets commented on moulin/builders/fota.py
> +        conf_bytes = serialized_conf.encode("ascii")
YAML node can contains non-ascii characters?

2023-05-10 23:44 UTC, lorc commented on moulin/ninja_syntax.py
> +                while text[space] == ' ':
Yes, please do not add unneeded patches

2023-05-11 09:07 UTC, dsemenets commented on docs/user-reference.rst
> +* Remains parameter should be parsed and used by script pointed in
Corrected

2023-05-11 09:07 UTC, dsemenets commented on moulin/builders/fota.py
> +        "rm -rf $work_dir",
This directory will consist only temporary files. Files remaining after previous run can corrupt resulted work

2023-05-11 09:07 UTC, dsemenets commented on moulin/builders/fota.py
> +        self.generator.build(local_conf_target, "fota_update_conf",   variables=dict(
Corrected

2023-05-11 09:11 UTC, dsemenets commented on docs/user-reference.rst
> +fota builder
custom_script is better

2023-05-17 13:02 UTC, lorc commented
I experimented with the code. For some reason, it triggers rebuild every time, which is incorrect. Please fix this

2023-05-24 08:49 UTC, dsemenets commented on moulin/ninja_syntax.py
> +                while text[space] == ' ':
Ok

2023-05-24 08:49 UTC, dsemenets commented on docs/user-reference.rst
> +    type: fota        # Should be 'fota'
Renamed

2023-05-24 08:54 UTC, dsemenets commented on moulin/builders/fota.py
> +        "rm -rf $work_dir",
Currently I don't remove that directory

2023-05-24 09:04 UTC, dsemenets commented
I have fixed triggering. You can review

2023-05-24 20:59 UTC, lorc reviewed
There a few fixes to the documentation and we are good to go

2023-05-24 20:59 UTC, lorc commented on docs/user-reference.rst
> +Fota builder is intended to perform custom actions. This builder
Not "fota builder" but "custom script builder"

2023-05-24 20:59 UTC, lorc commented on docs/user-reference.rst
> +    type: custom_script        # Should be 'fota'
"should be `custom_script'"

Please pay attention to what you are writing

2023-05-24 20:59 UTC, lorc commented on docs/user-reference.rst
> +custom_script builder
You added this section in the middle of Zephyr builder section. This is the third time I am pointing you at this. Please fix.

2023-05-24 20:59 UTC, lorc commented on docs/user-reference.rst
>  Proper versions of CMake and Zephyr SDK have to be installed on the host.
Third time I am pointing at this :)

2023-05-24 20:59 UTC, lorc commented on docs/user-reference.rst
> +    config1:
`config1`?

2023-05-24 20:59 UTC, lorc commented on docs/user-reference.rst
> +    additional_deps:  # Optional
This is malformed YAML document. Please add at least one `additional_deps` entry.

2023-05-25 08:50 UTC, dsemenets commented on docs/user-reference.rst
> +Fota builder is intended to perform custom actions. This builder
Fixed

2023-05-25 08:50 UTC, dsemenets commented on docs/user-reference.rst
> +    type: custom_script        # Should be 'fota'
Fixed

2023-05-25 08:51 UTC, dsemenets commented on docs/user-reference.rst
> +custom_script builder
Fixed

2023-05-25 08:52 UTC, dsemenets commented on docs/user-reference.rst
> +    additional_deps:  # Optional
Fixed

2023-05-25 08:55 UTC, dsemenets commented on docs/user-reference.rst
> +    config1:
Why not? For example config1 or config2. As you wish

2023-05-25 11:37 UTC, lorc approved these changes
With the last comment fixed:

`Reviewed-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

2023-05-25 11:37 UTC, lorc commented on docs/user-reference.rst
> -
Please remove this change. You concatenating two paragraphs into one. We don't need this.

2023-05-25 11:50 UTC, lorc commented
Ah, also please add commit that bumps up version, otherwise you will not be able to use it properly in your projects.

2023-05-25 14:16 UTC, dsemenets commented
Added version bump up commit

2023-05-25 15:03 UTC, merged