raise exception when have ambiguousness of revisions
xen-troops/moulin pull request #76
Opened 2023-06-05 14:34 UTC by iusyk

yaml file may have some ambiguousness of revisions, for example .....
domd:
    sources:
      - type: git url: "https://github.com/good/meta-good" .....
--ENABLE_SOMETHING
      default: no
      ......
         components:
            domd:
              sources:
                - type: git url: "https://github.com/good/meta-good" rev: main Here we have one repository but with the two different revisions. At this moment, moulin checks if url has been fetched and skip all the overrides. It means that build may have unexpected result. The patch check if the repos exists and if the revisions are the same. If revisions are not the same -  throws the exception.

2023-06-06 12:34 UTC, lorc requested changes

2023-06-06 12:34 UTC, lorc commented on moulin/fetchers/git.py
> +                self.git_rev != _SEEN_REPOS_REV.get(checkout_stamp)):
1. this is not C, so no need for parentheses in the `if` condition
2. There is no need to use `get`, you can use `[]` syntax. 
3. You missed the crucial point of returning stamp if it is already present. Now mulin will generate multiple "build" entries for each git repo which is bad

2023-06-06 12:34 UTC, lorc commented on moulin/fetchers/git.py
> +                            .format(
Please use string interpolation (aka f-stings) instead of `format`.

We want project source code to be consistent in used techniques.

2023-06-06 20:13 UTC, iusyk commented on moulin/fetchers/git.py
> +                self.git_rev != _SEEN_REPOS_REV.get(checkout_stamp)):
1. fixed
2. fixed
3. generator is closed, file is removed and ruining is stopped

2023-06-06 20:13 UTC, iusyk commented on moulin/fetchers/git.py
> +                            .format(
fixed

2023-06-06 22:20 UTC, lorc commented on moulin/fetchers/git.py
> +                self.git_rev != _SEEN_REPOS_REV.get(checkout_stamp)):
3. Whoa. You don't need to do all of this. Please remove all those changes, they are not necessary. 

My point was that original code issued `return checkout_stamp`. You removed this part, so now every call for the the same git repo will create a new `build` entry in the `build.ninja`.

2023-06-07 09:38 UTC, iusyk commented on moulin/fetchers/git.py
> +                self.git_rev != _SEEN_REPOS_REV.get(checkout_stamp)):
No, if everything is ok - we have 'return checkout_stamp' at the end of the function, if we have the same repo but different revisions - tool must be stopped. Bit yes, one case has not been considered correctly - when we have the same revisions, in this case call 'return checkout_stamp'.

2023-06-07 10:32 UTC, lorc requested changes
Let's stick only to git fetcher changes for now.

2023-06-07 11:11 UTC, iusyk commented on moulin/build_generator.py
> +from os import remove
then, we have not too much to do. 
1. leave as is (what is wrong) and close the PR
2. inform (via logging) user about the problem.
Raising the exception without the catching it does not make any sense.
The choice ?

2023-06-07 18:04 UTC, lorc commented on moulin/build_generator.py
> +from os import remove
> leave as is (what is wrong) and close the PR

Why? You made a valid change to `git.py`. I want to merge it.

> Raising the exception without the catching it does not make any sense.

Again, why? Python will catch it for us and write exception message with the trace log.

Look, I am not against more pretty error reporting, but it should be done properly:
1. In a separate commit (do not forget about atomic commits, please)
2. In `moulin_entry()` function, as it is main entry point. `moulin.py` is used only during local debugging. It is not installed and not used with `pip install`
3. Print exception backtrace, so user can trace  error to the correct place in the code. This is very important in case of YAML parsing exceptions, because it is not immediately obvious which code triggered an exception.
4.  Do the same for `rouge`
5. Use `log.error()`, not `print`
6. Cover all errors, not only `fetcher.gen_fetch()` call

2023-06-07 19:10 UTC, iusyk commented on moulin/build_generator.py
> +from os import remove
well, in the case if we relay on python - build.ninja will be generated, it is better to avoid it.
Backtrace - i think this is an error for user , not for developer to fix the bug, but backtrace is useful i agree
i review rouge as well to see what to do

2023-06-07 23:47 UTC, lorc commented on moulin/build_generator.py
> +from os import remove
As I said, backtrace can be handy for users to debug errors in YAML files, because backtrace allows user to see which component triggered an error.

2023-06-07 23:50 UTC, lorc commented
Can we limit this PR only to "one git repo, different revisions" bug fix? It is almost ready, you just need to remove unnecessary changes. We can merge it pronto.

You can open additional PR with enhanced error handling. I am envisioning that there will be much more discussions, so it will take much more time before it could be merged.

2024-01-26 12:03 UTC, closed without merging