Zephyr builder: Add escaping for the 'vars' parameter
xen-troops/moulin pull request #89
Opened 2023-11-13 19:00 UTC by Mishytca

Fix the issue with passing the "vars" parameters from the configuration moulin YAML file to the build.ninja context.

The 'vars' parameter of the Zephyr builder is placed into the bash -c "... cmd ..." context. It requires an additional level of escaping to be added to the 'vars' parameter.

But that is not enough. The 'vars' parameter is passed to the 'west build' call. West, in turn, passes those 'vars' parameter to CMake.

On the CMake level, Zephyr splits all incoming CMake parameters into 2 parts:

1. Those, which start with the "CONFIG_" prefix
2. All the others

The first group of parameters is stored in the KConfig file. When users pass a string to Kconfig through CMake, they are expected to pass it so that quotes are correct seen from Kconfig, that is:

> cmake -DCONFIG_A_STRING=\"foo bar\"

In this case, to obtain the required level of escaping:

- the first group of parameters should be additionally escaped twice on the moulin level
- the second group of parameters should be additionally escaped once on the moulin level

As a result of this patch, the user can specify the 'vars' on the yaml level in the following way:

        vars:
          - "CONFIG_KERNEL_BIN_NAME=\"%{KERNEL_BIN_NAME}\""
          - "MY_VARIABLE=\"1234567890\""

2023-11-13 19:37 UTC, lorc commented on moulin/builders/zephyr.py
> +            for el, var in enumerate(vars_vals):
I am okay with idea, but implementation is quite unpythonic. I'd prefer to have the next `if` block into a separate helper function. Something akin to `def _escape_env_var(var: str) ->str`. And here, instead of this `for` loop just write `vars_vals = [_escape_env_var(x.as_str) for x in vars_node]`

2023-11-13 19:42 UTC, lorc commented on moulin/builders/zephyr.py
> +                    # following the Zephyr documentation
It would be nice to have reference to that documentation part

2023-11-14 14:20 UTC, Mishytca commented on moulin/builders/zephyr.py
> +            for el, var in enumerate(vars_vals):
Hi, @lorc! Done.

2023-11-14 14:20 UTC, Mishytca commented on moulin/builders/zephyr.py
> +                    # following the Zephyr documentation
Hi, @lorc! Done.

2023-11-14 18:49 UTC, lorc requested changes
Please remember that commits should be atomic.

2023-11-14 18:49 UTC, lorc commented on docs/conf.py
> +release = 'v0.21'
This should be in a separate commit

2023-11-14 18:49 UTC, lorc commented on moulin/builders/zephyr.py
> +    def escape_vars_vals(self, var: str) -> str:
Any particular reason, why this should be a public non-static member of the class? As I can see, it does not touch `self` at all, also I see no reason to make it public.

2023-11-14 18:49 UTC, lorc commented on moulin/builders/zephyr.py
> +        https://github.com/tejlmand/zephyr/commit/4cb2ef83bfd1a4db3c37e66e1cf65bb6ec0145ef
Can we have link to the official Zephyr repo? I don't know who `tejlmand` are, but there is a chance that they can archive/remove their account and we'll get a dangling link.

2023-11-15 12:39 UTC, Mishytca commented on docs/conf.py
> +release = 'v0.21'
Hi, @lorc! Done.

2023-11-15 12:39 UTC, Mishytca commented on moulin/builders/zephyr.py
> +    def escape_vars_vals(self, var: str) -> str:
Hi, @lorc! Done.

2023-11-15 12:39 UTC, Mishytca commented on moulin/builders/zephyr.py
> +        https://github.com/tejlmand/zephyr/commit/4cb2ef83bfd1a4db3c37e66e1cf65bb6ec0145ef
Hi, @lorc! Done.

2023-11-15 16:25 UTC, merged