Dev/mykhailo androsiuk
xen-troops/moulin pull request #96
Opened 2024-01-05 20:06 UTC by Mishytca

The added test is focused on the issue:
issue with using identical Git repositories for different versions:
More details can be found here:
#91
The added test is focused on the issue:
issue with the usage of Poky default Layers:
More details can be found here:
#94

2024-01-08 22:01 UTC, lorc requested changes
Comments for the second patch are the same as for the first.

Also, it is unclear for which issue the first test is written . I reverted changes made by #92 and the test still passes. Could you please explain how I can verify it?

Also-also, commit description refers to "issue" in two meanings: the issue with moulin code (when it failed when should work) and user error. So it is unclear what "the issue mentioned above
is detected during its execution" exactly mean. Does the test should detect the issue in the mouling code? If yes, why it passes when the issue is fixed?

2024-01-08 22:01 UTC, lorc commented on tests/integration_tests/yocto_bulder/test_different_revisions_case/resources/test_different_revisions_case.yaml
> +desc: "Xen-Troops development setup for Renesas RCAR Gen3 hardware"
Nope :)

2024-01-10 20:21 UTC, Mishytca commented on tests/integration_tests/yocto_bulder/test_different_revisions_case/resources/test_different_revisions_case.yaml
> +        dir: "dir1"
Hi @lorc , done.

2024-01-10 20:22 UTC, Mishytca commented on tests/integration_tests/yocto_bulder/test_different_revisions_case/resources/test_different_revisions_case.yaml
> +
Hi @lorc , done.

2024-01-10 20:22 UTC, Mishytca commented on tests/integration_tests/yocto_bulder/test_different_revisions_case/test_different_revisions_case.py
> +    tmp_dir = os.path.join(script_dir_path, "tmp")
Hi @lorc , done.

2024-01-10 20:22 UTC, Mishytca commented on tests/integration_tests/yocto_bulder/test_different_revisions_case/resources/test_different_revisions_case.yaml
> +desc: "Xen-Troops development setup for Renesas RCAR Gen3 hardware"
Hi @lorc , done.

2024-01-10 20:22 UTC, Mishytca commented on tests/integration_tests/yocto_bulder/test_different_revisions_case/test_different_revisions_case.py
> +        print(result.stderr)
Hi @lorc , done.

2024-01-10 20:22 UTC, Mishytca commented on tests/unittest/test_build_generator.py
Hi @lorc , done.

2024-01-11 14:47 UTC, lorc approved these changes
Great, thanks

`Reviewed-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

2024-01-11 17:03 UTC, merged